server:
  port: 8079

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  mail:
    host: smtp.gmail.com
    port: 587
    username: akpeledavidprogress@gmail.com
    password: eruxeybiakedfjfp
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

pesco:
  banking:
    service:
      email: artexnetworkservice@gmail.com

file:
  upload-dir: src/main/resources/static/image

web:
  resources:
    static-locations: classpath:/static/

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, loggers, env
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans