global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # ── Spring Boot Services 
  - job_name: "auth-user-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["auth-user-service:8187"]

  - job_name: "wallet-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["wallet-service:8035"]

  - job_name: "deposit-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["deposit-service:8020"]

  - job_name: "withdraw-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["withdraw-service:8068"]

  - job_name: "escrow-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["escrow-service:8755"]

  - job_name: "notification-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["notification-service:8079"]

  - job_name: "revenue-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["revenue-service:8083"]

  - job_name: "admin-api-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["admin-api-service:8109"]

  - job_name: "virtual-card-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["virtual-card-service:8037"]

  # # ── .NET resiliences-service (/metrics is the default for ASP.NET) ────────
  # - job_name: "resiliences-service"
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ["resiliences-service:8531"]

  # ── Infrastructure ────────────────────────────────────────────────────────
  - job_name: "rabbitmq"
    metrics_path: /metrics
    static_configs:
      - targets: ["rabbitmq:15692"]   # RabbitMQ Prometheus plugin port