syntax = "proto3";

package wallet;

option java_multiple_files = true;
option java_package = "pesco.wallet_service.grpc";
option java_outer_classname = "WalletProto";

import "google/protobuf/timestamp.proto";

service WalletService {
    rpc GetWallet (GetWalletRequest) returns (WalletResponse);
    rpc UpdateBalance (UpdateBalanceRequest) returns (WalletResponse);
    rpc ListWallets (ListWalletsRequest) returns (ListWalletsResponse);
    rpc CreateTransferPin (CreateTransferPinRequest) returns (CreateTransferPinResponse);;
    rpc GetWalletSection (Empty) returns (WalletSectionResponse);
    rpc GetWalletSectionByUser (GetWalletSectionRequest) returns (WalletSectionResponse);
    rpc GetWalletByCurrency (GetWalletByCurrencyRequest) returns (WalletBalanceResponse);
    rpc WithdrawIn(WalletDeductionRequest) returns (WithdrawResponse);
    rpc TranferOut(TransferToUserRequest) returns (TransferResponse);
    rpc FindUserWalletPin (FindUserWalletPinRequest) returns (FindUserWalletPinResponse);
}

enum CurrencyType {
    USD = 0;
    EUR = 1;
    NGN = 2;
    GBP = 3;
    JPY = 4;
    AUD = 5;
    CAD = 6;
    CHF = 7;
    CNY = 8;
    INR = 9;
}

message TransactionRequest {
    string transfer_pin = 1;
}

message GetWalletSectionRequest {
    int64 user_id = 1;
  }

message CreateTransferPinRequest {
    string token = 1;
    TransactionRequest request = 2;
}

message CreateTransferPinResponse {
    string message = 1;
    string details = 2;
    int32 status_code = 3;
}

message WalletBalanceDTO {
    string currency_code = 1;
    string symbol = 2;
    string balance = 3;
}

message WalletSectionResponse {
    repeated WalletBalanceDTO wallet_balances = 1;
    int64 wallet_id = 2;
    bool has_transfer_pin = 3;
}

message Empty {}

message CurrencyBalance {
    string currency_code = 1;
    string currency_symbol = 2;
    string balance = 3; 
}

message WalletResponse {
    int64 id = 1;
    int64 user_id = 2;
    repeated CurrencyBalance balances = 3;
    google.protobuf.Timestamp created_on = 4;
    google.protobuf.Timestamp updated_on = 5;
}

message GetWalletRequest {
    oneof identifier {
        int64 id = 1;
        int64 user_id = 2;
    }
}

message UpdateBalanceRequest {
    int64 wallet_id = 1;
    CurrencyBalance balance_update = 2;
}

message GetWalletByCurrencyRequest {
    int64 user_id = 1;
    CurrencyType currency = 2;
}

message WalletBalanceResponse {
    int64 wallet_id = 1;
    string currency_code = 2;
    string symbol = 3;
    string balance = 4;
    int64 user_id = 5;
}

message ListWalletsRequest {
    int32 page = 1;
    int32 size = 2;
}

message ListWalletsResponse {
    repeated WalletResponse wallets = 1;
    int32 total_pages = 2;
    int32 current_page = 3;
}

message WithdrawResponse {
    string status = 1;
    string message = 2;
    string new_balance = 3;
    CurrencyType currency = 4;
}

message TransferResponse {
    string status = 1;
    string message = 2;
    string new_balance = 3;
    CurrencyType currency = 4;
}

message TransferToUserRequest {
    int64 user_id = 1;
    int64 wallet_id = 2;
    string recipient_bank_name = 3;
    string recipient_bank_holder_name = 4;
    string recipient_bank_account_number = 5;
    CurrencyType currency = 6;
    string amount = 7;
}

message WalletDeductionRequest {
    int64 user_id = 1;
    int64 wallet_id = 2;
    CurrencyType currency = 3;
    string amount = 4;
    string recipient_username = 5;
    string token = 6;
}


message FindUserWalletPinRequest {
  int64 wallet_id = 1;
}

message FindUserWalletPinResponse {
    int64 wallet_id = 1;
    string password = 2;
    bool isSecure = 3;
}