[package]
name = "nginx-security-tester-service"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
serde_json = "1.0"
rand = "0.9.1"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.6.6", default-features = false, features = ["cors"] }
hyper = { version = "1", features = ["full"] }
http = "1"
clap = { version = "4.5.44", features = ["derive"] }
reqwest = { version = "0.12.23", features = ["blocking", "json", "stream", "rustls-tls"] }
rand_core = "0.9.3"
async-trait = "0.1"
headers = "0.4"
thiserror = "2.0.15"
validator = { version = "0.20.0", features = ["derive"] }
sha2 = "0.10.9"
hex = "0.4.3"
bs58 = "0.5.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0.97"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }



[dev-dependencies]
tokio-test = "0.4.3"
criterion = "0.7.0"
tokio = { version = "1.0", features = ["full", "rt-multi-thread", "macros"] }
tempfile = "3.3"
http = "1"
http-body-util = "0.1"
hyper = "1"
tower-service = "0.3"
tower-layer = "0.3.2"
paste = "1.0"