global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: production
    project: epay

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: epay-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["epay-server:8029"]
        labels:
          service: epay-server
          language: java

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
