package com.example.admin_api_service.enums;

public enum ScheduledReportType {
    TRANSACTION_SUMMARY,
    TRANSACTION_DETAIL,
    WALLET_BALANCE_SUMMARY,
    USER_ACTIVITY,
    KYC_STATUS_SUMMARY,
    FEE_REVENUE,
    SETTLEMENT_SUMMARY,
    RECONCILIATION_SUMMARY,
    AML_ALERT_SUMMARY,
    CHARGEBACK_SUMMARY,
    LIQUIDITY_SUMMARY,
    COMPLIANCE_REPORT,
    RISK_SUMMARY,
    CUSTOM
}
