package com.example.admin_api_service.services;

import com.example.admin_api_service.Interfaces.IAmlAlertService;
import com.example.admin_api_service.Interfaces.IAmlCaseService;
import com.example.admin_api_service.enums.AmlAlertSeverity;
import com.example.admin_api_service.enums.AmlAlertStatus;
import com.example.admin_api_service.enums.AmlAlertType;
import com.example.admin_api_service.enums.AmlCasePriority;
import com.example.admin_api_service.enums.AmlCaseType;
import com.example.admin_api_service.exceptions.ConflictException;
import com.example.admin_api_service.exceptions.ResourceNotFoundException;
import com.example.admin_api_service.models.complianceAndRisk.AmlAlert;
import com.example.admin_api_service.models.complianceAndRisk.AmlCase;
import com.example.admin_api_service.models.complianceAndRisk.RiskRule;
import com.example.admin_api_service.repository.AmlAlertRepository;

import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

@Service
@Transactional
public class AmlAlertServiceImpl implements IAmlAlertService {

    private final AmlAlertRepository amlAlertRepository;
    private final IAmlCaseService amlCaseService;

    public AmlAlertServiceImpl(AmlAlertRepository amlAlertRepository,
                                @Lazy IAmlCaseService amlCaseService) {
        this.amlAlertRepository = amlAlertRepository;
        this.amlCaseService = amlCaseService;
    }

    @Override
    public AmlAlert raiseAlertFromRule(RiskRule rule, Long userId, Long walletId,
                                       String transactionId, String evidence) {
        AmlAlert alert = new AmlAlert();
        alert.setUserId(userId);
        alert.setWalletId(walletId);
        alert.setTransactionId(transactionId);
        alert.setRiskRuleId(rule.getId());
        alert.setAlertType(resolveAlertType(rule));
        alert.setSeverity(resolveSeverity(rule.getScoreWeight()));
        alert.setDescription("Triggered by rule: " + rule.getName());
        alert.setEvidence(evidence);
        alert.setRiskScore(BigDecimal.valueOf(rule.getScoreWeight()));
        alert.setAutoGenerated(true);
        alert.setStatus(AmlAlertStatus.OPEN);
        alert.setTriggeredAt(LocalDateTime.now());
        return amlAlertRepository.save(alert);
    }

    @Override
    public AmlAlert raiseManualAlert(Long userId, Long walletId, String transactionId,
                                     AmlAlertType alertType, AmlAlertSeverity severity,
                                     String description, BigDecimal amount, String currency,
                                     String evidence) {
        AmlAlert alert = new AmlAlert();
        alert.setUserId(userId);
        alert.setWalletId(walletId);
        alert.setTransactionId(transactionId);
        alert.setAlertType(alertType);
        alert.setSeverity(severity);
        alert.setDescription(description);
        alert.setAmount(amount);
        alert.setCurrency(currency);
        alert.setEvidence(evidence);
        alert.setAutoGenerated(false);
        alert.setStatus(AmlAlertStatus.OPEN);
        alert.setTriggeredAt(LocalDateTime.now());
        return amlAlertRepository.save(alert);
    }

    @Override
    @Transactional(readOnly = true)
    public AmlAlert getAlertById(String alertId) {
        return amlAlertRepository.findById(alertId)
                .orElseThrow(() -> new ResourceNotFoundException("AmlAlert", "id", alertId));
    }

    @Override
    @Transactional(readOnly = true)
    public Page<AmlAlert> getAllAlerts(Pageable pageable) {
        return amlAlertRepository.findAll(pageable);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<AmlAlert> getAlertsByStatus(AmlAlertStatus status, Pageable pageable) {
        return amlAlertRepository.findAllByStatus(status, pageable);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<AmlAlert> getAlertsBySeverity(AmlAlertSeverity severity, Pageable pageable) {
        return amlAlertRepository.findAllBySeverity(severity, pageable);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<AmlAlert> getAlertsByUser(Long userId, Pageable pageable) {
        return amlAlertRepository.findAllByUserId(userId, pageable);
    }

    @Override
    @Transactional(readOnly = true)
    public List<AmlAlert> getOpenAlertsForUser(Long userId) {
        return amlAlertRepository.findAllByUserIdAndStatus(userId, AmlAlertStatus.OPEN);
    }

    @Override
    public AmlAlert reviewAlert(String alertId, String reviewedBy, String reviewNote) {
        AmlAlert alert = getAlertById(alertId);
        validateAlertIsActionable(alert);
        alert.setStatus(AmlAlertStatus.UNDER_REVIEW);
        alert.setReviewedBy(reviewedBy);
        alert.setReviewedAt(LocalDateTime.now());
        alert.setReviewNote(reviewNote);
        alert.setUpdatedOn(LocalDateTime.now());
        return amlAlertRepository.save(alert);
    }

    @Override
    public AmlAlert escalateToCase(String alertId, String escalatedBy) {
        AmlAlert alert = getAlertById(alertId);
        validateAlertIsActionable(alert);

        // Create a new AML case linked to this alert
        AmlCase amlCase = amlCaseService.openCase(
                alert.getUserId(),
                alert.getWalletId(),
                AmlCaseType.SUSPICIOUS_TRANSACTION,
                AmlCasePriority.HIGH,
                "Escalated from alert: " + alertId,
                "Alert type: " + alert.getAlertType() + ". " + alert.getDescription(),
                escalatedBy
        );

        alert.setStatus(AmlAlertStatus.ESCALATED_TO_CASE);
        alert.setAmlCaseId(amlCase.getId());
        alert.setUpdatedOn(LocalDateTime.now());
        return amlAlertRepository.save(alert);
    }

    @Override
    public AmlAlert markFalsePositive(String alertId, String reviewedBy, String reviewNote) {
        AmlAlert alert = getAlertById(alertId);
        validateAlertIsActionable(alert);
        alert.setStatus(AmlAlertStatus.FALSE_POSITIVE);
        alert.setReviewedBy(reviewedBy);
        alert.setReviewedAt(LocalDateTime.now());
        alert.setReviewNote(reviewNote);
        alert.setUpdatedOn(LocalDateTime.now());
        return amlAlertRepository.save(alert);
    }

    @Override
    public AmlAlert closeAlert(String alertId, String closedBy, String note) {
        AmlAlert alert = getAlertById(alertId);
        alert.setStatus(AmlAlertStatus.CLOSED);
        alert.setReviewedBy(closedBy);
        alert.setReviewedAt(LocalDateTime.now());
        alert.setReviewNote(note);
        alert.setUpdatedOn(LocalDateTime.now());
        return amlAlertRepository.save(alert);
    }

    // ── Private helpers ────────────────────────────────────────────────────────

    private void validateAlertIsActionable(AmlAlert alert) {
        if (alert.getStatus() == AmlAlertStatus.CLOSED
                || alert.getStatus() == AmlAlertStatus.FALSE_POSITIVE
                || alert.getStatus() == AmlAlertStatus.ESCALATED_TO_CASE) {
            throw new ConflictException("Alert is already in a terminal state: " + alert.getStatus());
        }
    }

    private AmlAlertType resolveAlertType(RiskRule rule) {
        return switch (rule.getRuleType()) {
            case VELOCITY -> AmlAlertType.VELOCITY_DAILY_LIMIT;
            case SINGLE_TRANSACTION -> AmlAlertType.SINGLE_LARGE_TRANSACTION;
            case GEO -> AmlAlertType.HIGH_RISK_COUNTRY_TRANSFER;
            case SANCTION -> AmlAlertType.SANCTION_NAME_MATCH;
            case PATTERN -> AmlAlertType.UNUSUAL_PATTERN;
            default -> AmlAlertType.MANUAL_ALERT;
        };
    }

    private AmlAlertSeverity resolveSeverity(int scoreWeight) {
        if (scoreWeight >= 80) return AmlAlertSeverity.CRITICAL;
        if (scoreWeight >= 60) return AmlAlertSeverity.HIGH;
        if (scoreWeight >= 40) return AmlAlertSeverity.MEDIUM;
        return AmlAlertSeverity.LOW;
    }
}
