# proxy_hide_header X-Runtime;
# proxy_hide_header X-Powered-By;
# proxy_hide_header Server;

add_header X-Frame-Options "SAMEORIGIN" always;

add_header X-Content-Type-Options "nosniff" always;

add_header X-XSS-Protection "1; mode=block" always;

add_header Referrer-Policy "strict-origin-when-cross-origin" always;

add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https: blob: http://localhost:*; font-src 'self' https: data:; connect-src 'self' https: wss: ws: http://localhost:*; media-src 'self'; worker-src 'self' blob:; frame-ancestors 'self'; base-uri 'self'; form-action 'self'; object-src 'none';" always;

add_header Permissions-Policy "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), display-capture=(), encrypted-media=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=(), picture-in-picture=(self)" always;
add_header Cross-Origin-Opener-Policy "same-origin-allow-popups" always;
add_header Cross-Origin-Resource-Policy "cross-origin" always;
add_header X-Permitted-Cross-Domain-Policies "none" always;
proxy_hide_header X-Runtime;
proxy_hide_header X-Powered-By;
proxy_hide_header Server;