# HTTP Server Block
# Redirects all traffic to HTTPS, except ACME certificate challenges

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    # If you want to production then use this blow
    # listen 443 ssl http2;
    # server_name epay.yourdomain.com;
    
    # SSL Configuration
    # ssl_certificate /etc/nginx/ssl/epay.crt;
    # ssl_certificate_key /etc/nginx/ssl/epay.key;
    # ssl_session_cache shared:SSL:10m;
    # ssl_session_timeout 10m;
    # ssl_protocols TLSv1.2 TLSv1.3;
    # ssl_ciphers HIGH:!aNULL:!MD5;

    # Let's Encrypt / Certbot ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect everything else to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}
