// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using resiliences_service.Configs;

#nullable disable

namespace resiliences_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("resiliences_service.Models.Beneficiary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BankCode")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BankName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BeneficiaryType")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RecipientUsername")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .HasDatabaseName("idx_account_number");

                    b.HasIndex("RecipientUsername")
                        .HasDatabaseName("idx_recipient_username");

                    b.HasIndex("UserId", "BeneficiaryType")
                        .HasDatabaseName("idx_user_beneficiary");

                    b.HasIndex(new[] { "AccountNumber" }, "idx_account_number");

                    b.HasIndex(new[] { "RecipientUsername" }, "idx_recipient_username");

                    b.HasIndex(new[] { "UserId", "BeneficiaryType" }, "idx_user_beneficiary");

                    b.ToTable("beneficiaries");
                });

            modelBuilder.Entity("resiliences_service.Models.BlackListedWallet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BankBannedReason")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBlock")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WalletId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("BlackListedWallets");
                });

            modelBuilder.Entity("resiliences_service.Models.DebtCollector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "amount");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "createdOn");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "currencyType");

                    b.Property<string>("DebtStatus")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "debtStatus");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<decimal>("DueAmount")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "dueAmount");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedOn");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_debt_collector_user_id");

                    b.ToTable("DebtCollectors");
                });

            modelBuilder.Entity("resiliences_service.Models.History", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    b.Property<string>("AccountHolder")
                        .HasColumnType("text");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("AmlFlag")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ApprovalTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<decimal>("AvailableBalance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("BankCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Category")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Channel")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ComplianceNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CounterpartyAccountHolder")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("CounterpartyUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("CounterpartyWalletId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("DebitCredit")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DisputeReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DisputeStatus")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ErId")
                        .HasColumnType("text");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("FeeAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("GeoLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InitiatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("LedgerEntryType")
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("ManualAdjustmentFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("OriginalCurrency")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ParentHistoryId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    b.Property<decimal>("PreviousBalance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("text")
                        .HasColumnName("referenceNo");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReversalReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<decimal?>("RiskScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RoutingNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("RunningBalance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SanctionScreeningResult")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tags")
                        .HasColumnType("json");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TerminalId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("WalletId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ParentHistoryId");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("resiliences_service.Models.MaintenanceFeeHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AttemptedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "attemptedOn");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "currencyType");

                    b.Property<decimal>("FeeAmount")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "feeAmount");

                    b.Property<DateTime?>("PaidOn")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "paidOn");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedOn")
                        .HasDatabaseName("idx_maintenance_fee_history_attempted_on");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_maintenance_fee_history_user_id");

                    b.ToTable("MaintenanceFeeHistories");
                });

            modelBuilder.Entity("resiliences_service.Models.UserBankList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountHolderName")
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankCode")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.ToTable("UserBankLists");
                });

            modelBuilder.Entity("resiliences_service.Models.WalletMaintenance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "balance");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "createdOn");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "currencyType");

                    b.Property<DateTime?>("LastCharged")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "lastCharged");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedOn");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CurrencyType")
                        .IsUnique()
                        .HasDatabaseName("idx_wallet_maintenance_user_currency");

                    b.ToTable("WalletMaintenances");
                });

            modelBuilder.Entity("resiliences_service.Models.History", b =>
                {
                    b.HasOne("resiliences_service.Models.History", "ParentHistory")
                        .WithMany()
                        .HasForeignKey("ParentHistoryId");

                    b.Navigation("ParentHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
