package com.example.admin_api_service.enums;

public enum AccountRestrictionType {
    LOGIN_DISABLED,
    TRANSACTION_DISABLED,
    WITHDRAWAL_DISABLED,
    DEPOSIT_DISABLED,
    TRANSFER_DISABLED,
    DAILY_LIMIT_CAP,
    SINGLE_TRANSACTION_CAP,
    INTERNATIONAL_TRANSFER_BLOCKED,
    POS_DISABLED,
    USSD_DISABLED,
    API_ACCESS_DISABLED
}