package com.example.admin_api_service.enums;

public enum AmlAlertType {
    VELOCITY_DAILY_LIMIT,
    VELOCITY_WEEKLY_LIMIT,
    VELOCITY_MONTHLY_LIMIT,
    SINGLE_LARGE_TRANSACTION,
    ROUND_AMOUNT_PATTERN,
    MULTIPLE_SMALL_TRANSACTIONS,
    UNUSUAL_HOUR_ACTIVITY,
    HIGH_RISK_COUNTRY_TRANSFER,
    SANCTION_NAME_MATCH,
    PEP_MATCH,
    DORMANT_ACCOUNT_ACTIVITY,
    RAPID_FUND_MOVEMENT,
    COUNTERPARTY_RISK,
    MANUAL_ALERT,
    UNUSUAL_PATTERN
}
