package com.example.admin_api_service.enums;

public enum ApprovalWorkflowType {
    MANUAL_ADJUSTMENT,
    WALLET_FREEZE,
    WALLET_UNFREEZE,
    ACCOUNT_RESTRICTION,
    BULK_DISBURSEMENT,
    BULK_DEBIT,
    BULK_FREEZE,
    FEE_CONFIGURATION_CHANGE,
    TRANSACTION_LIMIT_OVERRIDE,
    KYC_APPROVAL,
    CHARGEBACK,
    REVERSAL,
    SYSTEM_CONFIGURATION_CHANGE,
    LIQUIDITY_TRANSFER
}
