apiVersion: 1

datasources:

  - name: Prometheus
    type: prometheus
    uid: prometheus-uid
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    type: loki
    uid: loki-uid
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '\[([0-9a-f]{16,32}),'
          url: http://localhost:9411/zipkin/traces/$${__value.raw}
          urlDisplayLabel: "Open in Zipkin"