server:
  port: 8068

spring:
  application:
    name: withdraw-service

jwt:
  secret-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnBaWj2t3CwC6kxlhHYxKs2eirgl0kYohe6MZaNKS7XbS1zWlM2xZlaY9fUZbn9jlGGaKWci2gaGBU45JXAqzlpQbuWiMYavcfG19kB1dBNy6vOH++uJSEPNud7EwaBpdY9YENMkKKcEkTAZNXhifGGcSlAaBQ9NZmYdG5bTBiht1TsQk19GLOcS9DftjlAk7EadAVnfJBLLnVgZxBDTMP5L4LW1EMAS8y8Lwp98LWu7T3OfejnUMbH2AWd5FXYDZI1TXHhVMLVmM08ZZr0HpoLevjwCgv7CMhtvm7q6wIDAQABlcBCilFEQT0SWEZcCQhGx2UaCZcxPx4bYBfrGM0DVKDJycK2UL4dDJqAkZ8r4IBQxSa3S2wlTVlnVVzvzP5sfzPtLUournmEY2N3ZGVnQ1BtWEF0anZ0aDNLNHJhaHh9IkFVaj0PXA

flutterwave:
  public-key: FLWPUBK_TEST-9f86808391a0bef01975c332a2782e5a-X
  secret-key: FLWSECK_TEST-1eee27f63b4dc12394dbf5c7badaa39e-X
  url: https://api.flutterwave.com/v3

paystack:
  api:
    url: https://api.paystack.co
    key: sk_test_aaa8ff310f15a0ad5f23950a584f8942cbdf02aa

revenue-service:
  base-url: http://revenue-service:8083
  
blacklist-service:
  base-url: http://blacklist-service:8013
  
history-service:
  base-url: http://history-service:8390

wallet-service:
  base-url: http://wallet-service:8035

wallet-websocket:
  url: ws://wallet-service:8035/ws/wallet

auth-service:
  base-url: http://authentication-service:8187

banklist-service:
  base-url: http://banklist-service:8040

notification-service:
  base-url: http://notification-service:8079

escrow-service:
  base-url: http://escrow-service:8755

logging:
  level:
    org.springframework.security: DEBUG
    
grpc: 
  client:
    wallet-service:
      address: static://wallet-service:9090  
      negotiationType: plaintext

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans