server:
  port: 8020

spring:
  application:
    name: deposit-service

geolocation:
  ip-api:
    base-url: http://ip-api.com
    timeout-seconds: 3
  cache:
    max-size: 5000
    expire-hours: 24
jwt:
  secret-key: 3hbXrhqhmvPD0bVq9Ce4hxTqALG701J7jRXyfKjqtzDPIlbdJ8YMIfZtHmPlC6Js9JVpELE2tj4KGP1VoCMA4Ya58WGF3Hs1
flutterwave:
  public-key: FLWPUBK_TEST-9f86808391a0bef01975c332a2782e5a-X
  secret-key: FLWSECK_TEST-1eee27f63b4dc12394dbf5c7badaa39e-X
  url: https://api.flutterwave.com/v3

paystack:
  api:
    url: https://api.paystack.co
    key: sk_test_aaa8ff310f15a0ad5f23950a584f8942cbdf02aa
  
history-service:
  base-url:  http://resiliences-service:8531

wallet-service:
  base-url: http://wallet-service:8035

wallet-websocket:
  url: ws://wallet-service:8035

auth-service:
  base-url:  http://authentication-service:8080

banklist-service:
  base-url:  http://resiliences-service:8531

notification-service:
  base-url:  http://notification-service:8079

grpc: 
  client:
    wallet-service:
      address: static://wallet-service:9090  
      negotiationType: plaintext

logging:
  level:
    com.mouad.movieservice: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, loggers, env
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
