package com.example.admin_api_service.models.complianceAndRisk;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import com.example.admin_api_service.enums.AmlAlertSeverity;
import com.example.admin_api_service.enums.AmlAlertStatus;
import com.example.admin_api_service.enums.AmlAlertType;

@Entity
@Table(name = "aml_alerts")
public class AmlAlert {

    @Id
    @Column(name = "id", length = 36, nullable = false, updatable = false)
    private String id = UUID.randomUUID().toString();

    // Optional — null until alert is escalated into a case
    @Column(name = "aml_case_id", length = 36)
    private String amlCaseId;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    @Column(name = "wallet_id")
    private Long walletId;

    // Transaction that triggered this alert
    @Column(name = "transaction_id", length = 36)
    private String transactionId;

    // Risk rule that fired
    @Column(name = "risk_rule_id", length = 36)
    private String riskRuleId;

    @Enumerated(EnumType.STRING)
    @Column(name = "alert_type", length = 50, nullable = false)
    private AmlAlertType alertType;

    @Enumerated(EnumType.STRING)
    @Column(name = "severity", length = 20, nullable = false)
    private AmlAlertSeverity severity = AmlAlertSeverity.MEDIUM;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 20, nullable = false)
    private AmlAlertStatus status = AmlAlertStatus.OPEN;

    @Column(name = "description", length = 1000, nullable = false)
    private String description;

    // Computed score from risk engine (0.00 – 100.00)
    @Column(name = "risk_score", precision = 5, scale = 2)
    private BigDecimal riskScore;

    // Amount involved in the triggering transaction
    @Column(name = "amount", precision = 18, scale = 4)
    private BigDecimal amount;

    @Column(name = "currency", length = 10)
    private String currency;

    // Raw evidence from the rule engine stored as JSON
    @Column(name = "evidence", columnDefinition = "json")
    private String evidence;

    @Column(name = "reviewed_by", length = 36)
    private String reviewedBy;

    @Column(name = "reviewed_at")
    private LocalDateTime reviewedAt;

    @Column(name = "review_note", length = 500)
    private String reviewNote;

    // Whether this alert was automatically generated or manually raised
    @Column(name = "is_auto_generated", nullable = false)
    private boolean isAutoGenerated = true;

    @Column(name = "triggered_at", nullable = false)
    private LocalDateTime triggeredAt = LocalDateTime.now();

    @Column(name = "created_on", nullable = false, updatable = false)
    private LocalDateTime createdOn = LocalDateTime.now();

    @Column(name = "updated_on", nullable = false)
    private LocalDateTime updatedOn = LocalDateTime.now();

    // Navigation
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "aml_case_id", insertable = false, updatable = false)
    private AmlCase amlCase;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "risk_rule_id", insertable = false, updatable = false)
    private RiskRule riskRule;

    @PreUpdate
    public void preUpdate() {
        this.updatedOn = LocalDateTime.now();
    }

    public AmlAlert() {
    }

    public AmlAlert(String id, String amlCaseId, Long userId, Long walletId, String transactionId, String riskRuleId, AmlAlertType alertType, AmlAlertSeverity severity, AmlAlertStatus status, String description, BigDecimal riskScore, BigDecimal amount, String currency, String evidence, String reviewedBy, LocalDateTime reviewedAt, String reviewNote, boolean isAutoGenerated, LocalDateTime triggeredAt, LocalDateTime createdOn, LocalDateTime updatedOn, AmlCase amlCase, RiskRule riskRule) {
        this.id = id;
        this.amlCaseId = amlCaseId;
        this.userId = userId;
        this.walletId = walletId;
        this.transactionId = transactionId;
        this.riskRuleId = riskRuleId;
        this.alertType = alertType;
        this.severity = severity;
        this.status = status;
        this.description = description;
        this.riskScore = riskScore;
        this.amount = amount;
        this.currency = currency;
        this.evidence = evidence;
        this.reviewedBy = reviewedBy;
        this.reviewedAt = reviewedAt;
        this.reviewNote = reviewNote;
        this.isAutoGenerated = isAutoGenerated;
        this.triggeredAt = triggeredAt;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
        this.amlCase = amlCase;
        this.riskRule = riskRule;
    }

    // Getters & Setters
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getAmlCaseId() { return amlCaseId; }
    public void setAmlCaseId(String amlCaseId) { this.amlCaseId = amlCaseId; }

    public Long getUserId() { return userId; }
    public void setUserId(Long userId) { this.userId = userId; }

    public Long getWalletId() { return walletId; }
    public void setWalletId(Long walletId) { this.walletId = walletId; }

    public String getTransactionId() { return transactionId; }
    public void setTransactionId(String transactionId) { this.transactionId = transactionId; }

    public String getRiskRuleId() { return riskRuleId; }
    public void setRiskRuleId(String riskRuleId) { this.riskRuleId = riskRuleId; }

    public AmlAlertType getAlertType() { return alertType; }
    public void setAlertType(AmlAlertType alertType) { this.alertType = alertType; }

    public AmlAlertSeverity getSeverity() { return severity; }
    public void setSeverity(AmlAlertSeverity severity) { this.severity = severity; }

    public AmlAlertStatus getStatus() { return status; }
    public void setStatus(AmlAlertStatus status) { this.status = status; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public BigDecimal getRiskScore() { return riskScore; }
    public void setRiskScore(BigDecimal riskScore) { this.riskScore = riskScore; }

    public BigDecimal getAmount() { return amount; }
    public void setAmount(BigDecimal amount) { this.amount = amount; }

    public String getCurrency() { return currency; }
    public void setCurrency(String currency) { this.currency = currency; }

    public String getEvidence() { return evidence; }
    public void setEvidence(String evidence) { this.evidence = evidence; }

    public String getReviewedBy() { return reviewedBy; }
    public void setReviewedBy(String reviewedBy) { this.reviewedBy = reviewedBy; }

    public LocalDateTime getReviewedAt() { return reviewedAt; }
    public void setReviewedAt(LocalDateTime reviewedAt) { this.reviewedAt = reviewedAt; }

    public String getReviewNote() { return reviewNote; }
    public void setReviewNote(String reviewNote) { this.reviewNote = reviewNote; }

    public boolean isAutoGenerated() { return isAutoGenerated; }
    public void setAutoGenerated(boolean autoGenerated) { isAutoGenerated = autoGenerated; }

    public LocalDateTime getTriggeredAt() { return triggeredAt; }
    public void setTriggeredAt(LocalDateTime triggeredAt) { this.triggeredAt = triggeredAt; }

    public LocalDateTime getCreatedOn() { return createdOn; }
    public void setCreatedOn(LocalDateTime createdOn) { this.createdOn = createdOn; }

    public LocalDateTime getUpdatedOn() { return updatedOn; }
    public void setUpdatedOn(LocalDateTime updatedOn) { this.updatedOn = updatedOn; }

    public AmlCase getAmlCase() { return amlCase; }
    public void setAmlCase(AmlCase amlCase) { this.amlCase = amlCase; }

    public RiskRule getRiskRule() { return riskRule; }
    public void setRiskRule(RiskRule riskRule) { this.riskRule = riskRule; }
}
